package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'CxxCiDemo_Main_DemoProjectA'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("CxxCiDemo_Main_DemoProjectA")) {
    val expected = GitVcsRoot({
        id("CxxCiDemo_Main_DemoProjectA")
        name = "demo-project-a"
        url = "http://gitlab:8929/root/demo-project-a.git"
        branch = "%branch_default%"
        branchSpec = "%branch_spec%"
        checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
        authMethod = password {
            userName = "root"
            password = "%gitlab_credentials_password%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "root"
            password = "credentialsJSON:ed2e40ed-f84e-429a-85c6-90844f5e6b42"
        }
    }

}
