package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'CxxCiDemo_Main'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("CxxCiDemo_Main")) {
    params {
        expect {
            password("gitlab_credentials_password", "")
        }
        update {
            password("gitlab_credentials_password", "credentialsJSON:f334f54e-6d8a-48a8-aa0d-117995e9bb37")
        }
    }
}
