package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'CxxCiDemo_Main'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("CxxCiDemo_Main")) {
    params {
        expect {
            password("gitlab_credentials_password", "")
        }
        update {
            password("gitlab_credentials_password", "credentialsJSON:ed2e40ed-f84e-429a-85c6-90844f5e6b42")
        }
    }
}
